dgud/wings

- src/wings_extrude_edge.erl
Export so plugins may use this extrude_edges function.
> Export so plugins may use this extrude_edges function.

- src/wings_menu.erl
It was noticed the hotkey string wasn't displayed in popup menu for some
options. I found it was related to menu items which type=submenu. It was needed
to change the way they were processed into normalize_menu_wx and how the popup
menu was built.
> Fixed some hotkey string not present in the menu option

- unix/wings.appdata.xml
I've notified original author about inclusion. See this PR for further
details:
https://github.com/hughsie/fedora-appstream/pull/164
Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>
> Remove leftover comment from appdata

- src/wings_face_cmd.erl
The current Bridge command decides with vertices to connect, but there are
some situation in which we want to decide which vertice must be used as
reference. That allow us to create a twisted bridge.
> Added new Bridge with reference option

- src/wings_dialog.erl
- Fixed the Info dialogs not getting focused;
- Fixed the slide/text not calling user hook.
> Fixes to v2.0.5 (b)

- plugins_src/primitives/wpc_cylinder.erl
- plugins_src/primitives/wpc_geodome.erl
- plugins_src/primitives/wpc_knot.erl
- plugins_src/primitives/wpc_ncube.erl
- plugins_src/primitives/wpc_plane.erl
- plugins_src/primitives/wpc_spiral.erl
- plugins_src/primitives/wpc_torus.erl
- plugins_src/primitives/wpc_tt.erl
- src/wings_shapes.erl
- Added dialog option to Octahedron and Octotoad objects;
- Added new options: Rotate, Move and Put On Ground;
- It was standardized the dialogs by using label_column always as possible.
> Improved the primitive dialogs

- src/wings_edge_cmd.erl
NOTE:
Added new connect and slide command for Connect RMB in Edge mode. Thanks to
tkbd for suggest it.
> New RMB option for Connect command

- src/wings_geom_win.erl
NOTE: Object count for each folder in Geometry Graph was missing. Thanks to tkbd
> It was added objects count to folders in Geometry Graph

- plugins_src/commands/wpc_sel_win.erl
- plugins_src/import_export/collada_import.erl
- plugins_src/import_export/wpc_stl.erl
- plugins_src/primitives/wpc_image.erl
- src/wings_ff_wings.erl
- src/wings_file.erl
- src/wings_image_viewer.erl
- src/wings_material.erl
- Fixed the 'Add To'/'Subtract From' selection group operations;
- Fixed [In outliner, Crashed when preview to UTF8 name image](http://www.wings3d.com/forum/showthread.php?tid=2304);
- Some partial fixes related to unicode issues reported by tkbd in this thread: [(UTF8 DATA Import)Crashed or Mojibaked when import with an data name that contain UTF](http://www.wings3d.com/forum/showthread.php?tid=2321). Those errors in logs for 3ds, Collada(dae) and Stl should be fixed;
OBS: I put each one in a commit as well as a comment too, so you can pick then if you find them appropriated.
> Mv/fixes v2.1.5a

- src/wings_collapse.erl
https://github.com/dgud/wings/issues/253
When collapsing faces, edges, or vertices around holes, the
hole faces could be deleted, but still be marked as holes. That
would lead to a crash when attempting to save the file or when
using the Combine command. The Collapse command now makes sure
that holes for any deleted faces are removed.
> Teach Collapse command to remove holes for deleted faces

- src/wings_menu.erl
- Added missing option to add a checked menu item
_ * It's just for your information in case you decide to build a new version. I may add further fixes to this pull request._
> Fixes for 2.1.6

- src/wings_image.erl
NOTE: Fixed the hard crash when creating a texture.
> Fixed a hard crash caused by wings_image module

- src/wings_info.erl
NOTE: The information line was showing a wrong value for the edge difference
and angle info was also missing. Thanks to rv3.
> Fixed the informations for two selected edges

- src/wings.erl
NOTE: Enabled the Flatten command to be repeatable in edge mode. Thanks to Hank.
> Flatten command couldn't be repeated to a edge

- src/wings_frame.erl
The windows layout was getting messed each time we load Wings3D.
> Fixed the widows layout issue

- src/wings_dialog.erl
It was added code in order to make possible to update an image control in
case of we change it's value (i.e. file name or image id).
> Dialog module can now update a preview image

- plugins_src/autouv/wpc_autouv.erl
By checking an issue related to Select Similar Material in AutoUV window
I found that we had other asleep bugs since v2.0. It was removed all possible
causes of crash in AutoUV window when the user make use of some Select commands.
The commands: Similar Material, Similar Area and Similar Normals, creates
a preview dialog which I was not able to make they work properly (do a correct
selection in AutoUV window) - even changing the code to create a custom
function to handle the dialog events (preview_dialog/cancel/Res). Then, I
choose to handle these commands in wpc_autouv module and call the commands
in wings_sel module using the default values for its parameters (or the one
stored in preferences).
Reported here: http://www.wings3d.com/forum/showthread.php?tid=2748
**_It's interesting to …
> Fixed some cause of crashes in AutoUV window related to Select menu

- plugins_src/autouv/wpc_autouv.erl
This option was moved from AutoUV window to Show menu  during the migration
to wx library. It's very handy we have it very close to our work on the UV
mesh. To get it available the AutoUV window must to be active and sometimes
moving the mouse from AutoUV window to Show menu results in other window
grab the focus and the option becomes not acessible.
NOTE: Added the toggle background option to the AutoUV window.
> Added the toggle background option back to the AutoUV window

- src/wings_hotkey.erl
If we were bind a hotkey that was own by a main menu item Wings3D was asking
for replace it, but was not really doing that. Also, a try to set a hotkey
back to the main menu was not updating it as well as removing the previous
command that was using it.
NOTE: Binding a hotkey used by main menu was not removing it. Thanks yschaeff
> Fixed an hotkey isseue related to main menu shortcuts

- src/wings_menu.erl
The context menu on geometry window can get the bottom portion hidden by the
task bar. Also, if the user hit RMB with the menu shown the menu can be cut
once the new top location is the mouse position.
It was used wsDisplay information to compute the correct location of a menu
on a display where the mouse was used to invoke it. The getClientArea function
takes in account the taskbar if it's present. That ensure we don't get any
portion of the menu hidden by it as well as we can deal correctly with system
with multiple monitors.
NOTE: Context menu on Geometry can get options hidden. Thanks to nigec.
> Context menu on Geometry window always fits inside the display

- src/wings_body.erl
NOTE: Changed Separate command in order to keep all object selected.
Thanks to tkbd for the suggestion
> Changed Separate command to keep all objects selected

- plugins_src/import_export/wpc_yafaray.erl
Hello @Micheus  and @dgud 
I think this time I got a better idea about how to do this properly, thank you for your advice!  I hope this time this is acceptable.
If this is all ok and you accept the pull request then please @Micheus stop working in my fork and please let's both of us continue working in the future sending pull requests to the base dgud/wings repository, I think it will make our lives much easier from now on.
Thanks for your interest in YafaRay! :-)
PS: I'm preparing *a lot* of internal code changes in the upcoming YafaRay v4. Mostly sanitizing the code, making it easier to understand and hopefully to maintain but also changing the interfaces for future feature improvements, etc. It's still too early to prepare a Wings3D plugin for it but when the time comes, do you prefer …
> YafaRay Plugin: Merging Unicode and missing params fixes from Micheus,

- plugins_src/primitives/Makefile
- plugins_src/primitives/wpc_thread.erl
The new item will be placed just after the **Spring** on the context menu.
NOTE: Added new primitive screw thread
> New primitive thread (screw thread)

- plugins_src/import_export/wpc_stl.erl
- Fixed the crash in drag and drop feature which was introduced by the changes 
to STL importer/exporter menu definition (in commit c24d47e);
> Fixed the drag images issue introduced with the STL changes

- plugins_src/autouv/wpc_autouv.erl
This command must make easier to get proper textures when we are using a image
pattern (tilable) which we can scale the mesh to fill the max width or height of
the UV space in order to get the pattern replicated in the entire mesh and
without any seam visible.
The current behaviour was not changed: LMB will act as it used too. The new options were added to MMB a and RMB.
NOTE:
- Added option to scale uniformly the UV to the max U or max V.
> Added option to scale max uniform UV to max U or max V

- src/wings_geom_win.erl
A red cube is shown in front the folder if any object not in the root of the tree is selected.
NOTE: Folders in Geometry Graph now includes an icon to indicate which ones
are hosting the selected objects. Thanks Hank for the suggestion.
> Added a visual feedback to sign which folders are hosting the selections

- src/wings_dialog.erl
To avoid bugs, which we have seen several of, when a dialog (with preview)
is open, make all dialogs modal.
This avoids that you can open menus from other windows when a dialog is open,
you can not attach windows, which have caused issues in the past.
> Make all dialogs modal

- plugins_src/import_export/wpc_yafaray.erl
These properties were missing.
The 'Cast shadows' was removed in 2015 by oort due some changes in yafaray
in that time.
NOTE:
- Added 'Cast Shadows' property to the lights's dialog and the 'Visibility'
property to the 'Object Parameters' tab in Yafaray Material dialog.
> YafaRay plugin: Added cast shadows and visibility properties

- src/wings_file.erl
I accidentally reversed my project without any warnings when I choose the Revert
command instead of Render on the main menu File.
NOTE:
- Added a warning for Revert command on the  main menu File.
> Added a warning on reverting the project

- src/wings_light.erl
It was added code to store the pre-computed environment maps data in the cache
folder. The files get the '.emc' extension which stands for 'Environment Maps
Cache'. For the current settings (MMs) the file size is 9MB.
In case of fail to reading the file it is deleted and the code to create the
environment maps on-the-fly will run.
Even the default 'grandcanyon' image will be cached, so the loading time and
the switching process to other environment maps starts to happen in no time.
The fake_envmap process stays the same, but it could be redesigned to use the
same file cache approach with the file being packed with Wings3D.
> Added support for fast loading environment maps

- plugins_src/commands/wpc_connect_tool.erl
- plugins_src/commands/wpc_plane_cut.erl
- plugins_src/import_export/wpc_gltf.erl
- plugins_src/import_export/wpc_ps.erl
- plugins_src/import_export/wpc_yafaray.erl
- plugins_src/primitives/wpc_thread.erl
- shaders/ambient_light.fs
- shaders/area_light.fs
- shaders/camera_light.fs
- shaders/lib_base.glsl
- shaders/lib_envlight.glsl
- src/wings_cl.erl
- src/wings_view_win.erl
PR has been broken in to several commits for more convenient review and cherrypicking. **Note:** These fixes have not been tested
> Fix misc. source typos

- src/wings_frame.erl
> remove redefined 'wxID_OSX_*` macros

- plugins_src/import_export/Makefile
- plugins_src/import_export/wpc_wrl.erl
- plugins_src/import_export/x3d_import.erl
- plugins_src/import_export/x3d_import__sgi.erl
I added X3D and VRML import to complement the VRML exporter, and also added X3D output for the exporter too.
> X3D and VRML import, X3D export for wpc_wrl

- plugins_src/import_export/Makefile
- plugins_src/import_export/wpc_x.erl
- plugins_src/import_export/x_import.erl
I added .x import to complement the .x export part of wpc_x.
> Added .x file import to wpc_x

- plugins_src/import_export/wpc_svg_path.erl
I've improved the handling of the transform attribute in wpc_svg_path, including changes to the matrix concatenation, support for nested element transforms, support for three argument rotate(angle x y), and fixes to skewX and skewY.
NOTE: Improved transform attribute handling
> wpc_svg_path: Improved handling of transform attribute

- plugins_src/import_export/Makefile
- plugins_src/import_export/wpc_wmf_file_paths.erl
- plugins_src/import_export/wpc_wmf_paths.erl
An importer that imports .wmf and .emf paths.
It's been tested and works well with emf and wmf files exported from a few programs including Inkscape.
> New importer EMF and WMF paths plugin

- plugins_src/import_export/x_import.erl
I've made several fixes to the .x mesh importer based on files that didn't load for various reasons. I've also added binary and compression support.
Thanks tkbd for finding files with corner cases to fix.
NOTE: Several fixes to x_import, added binary and compression support. Thanks tkbd for finding .x files to fix the importer with.
> x_import: Several fixes and added binary and compression support

- plugins_src/import_export/wpc_x.erl
I noticed while testing the importer that the directx exporter didn't have an handedness option, left handed will reverse the face direction and invert the z axis, while right handed is the same as before.
NOTE: Added handedness option for DirectX export
> Added handedness option for DirectX export

- plugins_src/primitives/Makefile
- plugins_src/primitives/wpc_oblong.erl
New shape inspired by Christophe Blattmann's plugin for 3dsMax (https://www.christopheblattmann.com/oblong)
NOTE: New primitive Oblong
> New shape named Oblong

- plugins_src/import_export/wpc_collada.erl
NOTE: When objects and materials was including invalid charactes the .dae file couldn't be imported by other applications. Thanks to Wҽɳԃιҽ Bʅαƈƙƚԋσɾɳ
> Fixed an issue related to invalid characters object and material naming

- plugins_src/primitives/wpc_plane_it.lang
- src/wings_it.lang
Added Italian translation provided the user Drakan1955. Thanks.
> Italian translation

- plugins_src/import_export/Makefile
- plugins_src/import_export/wpc_3mf.erl
An importer and exporter plugin for 3MF (3D Manufacturing File), similar to AMF it is a format designed for 3d printing.
NOTE: Importer and exporter for 3MF (3D Manufacturing File)
> 3MF (3D manufacturing file) importer and exporter

- src/wings_import.erl
- src/wings_we.erl
- src/wings_we_build.erl
Include more edges as possibilties when trying to deduce hard-edges from vertex normals.
Solves #586
> e3d: Be less restrictive when calculating hard-edges

- plugins_src/primitives/wpc_ncube.erl
- plugins_src/primitives/wpc_oblong.erl
- Fixed a soft crash in wpc_ncube caused by computed value of  -0.0;
- Fixed the constant EPISILON used in wpc_oblong;
> More fixes related to otp27 compatibility

- plugins_src/primitives/wpc_cylinder.erl
NOTE:
- It was added the new type "Pie" to the Cylinder primitive as well as its necessary parameters: Degrees and Angle Offset.
> Added a new option to Cylinder type: Pie

- plugins_src/primitives/wpc_cylinder.erl
Fixed the sections count which was missing one. Thanks to ivla
> Fixed an issue in Pie primitive

- plugins_src/autouv/auv_texture.erl
- plugins_src/autouv/wpc_autouv.erl
- src/wings_outliner.erl
NOTE:
- Create Texture with Background layer was not accepting the image. Thanks to Wҽɳԃιҽ Bʅαƈƙƚԋσɾɳ
- Drag and Drop textures on AutoUV was not working;
- AutoUV was not getting updated when an image was dragged and 
dropped in Outline from Images to Materials
> AutoUV texture issues

- plugins_src/import_export/wpc_collada.erl
This new option was a user request which I thought it would have some value to be implemented.
A check box option is appended to the exporter dialog allowing the user decide to export this information or not. The default value is false, so it doesn't change the usual users' workflow.
NOTE
- Added option to include camera/views settings in Collada exporter. Thanks to
ismacou (suggestion) and @Vaughan
> Added new option to export camera in Collada exporter
