src/wings_ff_ndo.erl

These debugging outputs clutter the console at various times.

Remove io debugging statements from nendo module.

---

src/wings_dialog.erl

The "case" clause was coded as it was an "if" clause.

Fixed a crash caused by the table control result

---

plugins_src/commands/ambocc_gl2.erl
plugins_src/commands/wpc_ambocc.erl
src/wings_draw_setup.erl

aa3007d189d7 added a double deallocation of VBOs. The VBOs in
question had been created by wings_draw_setup:we/3, which in turn
called wings_dl to save them in the garbage collected system
"display lists". Therefore, the Ambient Occlusion plug-in must
not try to delete the VBOs itself, since wings_dl will do
the deletion during its garbage collection.
wings_draw_setup:delete_vab/1 can be removed, since the Ambient
Occlusion plug-in was the last caller.
NOTE: Fixed the problem with crash in the Ambient Occlusion plug-in.

Eliminate crash in Ambient Occlusion

---

plugins_src/primitives/wpc_plane.erl

NOTE: Moving the mouse over 'Various Plans' dialog icon was causing Wings3d
crash. Thanks to tkbd.

Fixed crash when mouse over 'Various Plane' dialog icon

---

src/wings_body.erl
src/wings_face_cmd.erl
src/wings_subdiv.erl

Currently, if someone wants to just subdivide a face or object without smooth
the faces he/she needs to set the edges to hard first.
NOTE: It was added a new Subdivide(RMB) command to be side-by-side with
Smooth (Catmull Clark) command. Suggested by Arg Arg.

Added new Subdivide option.

---

src/wings.erl
src/wings_frame.erl

By tracking the code it was not possible to find a way the splitters be
arranged in the saved location. The way the windows are created doesn't
allow us to do that. So, as an alternative, after all the windows has been
created and arranged in the proper layout we call a new function that set
the splitter position correctly.
It was also include a few lines to save the window size that is of interest
of us to be restored next time Wings3d is started. It's preserve its old
location is also desired, but not included in this branch.

That is a suggestion to fix the layout issue.

---

src/wings_menu.erl

Because of in menues we can show only the shortcut for the LMB option and
because the user may need to know the others defined to MMB and RMB it was
added these information to the menu hint/tooltip.
We came to this solution due to tkbd's thread: "Dilemma of hotkeys"
(http://www.wings3d.com/forum/showthread.php?tid=1906&pid=9919)

Added hotkey info to the tooltip text.

---

src/wings_view.erl

- Added two new camera formats (4:3 and 16:9) to the 'Negative Format' list
Suggested by tkbd;
- Fixed an enable/disable Width and Heigh fields that should be enabled
only for Custom format.

Added new camera formats to the Camera dialog

---

src/wings_dialog.erl
src/wings_file.erl
src/wings_material.erl

- Added the missing support to user hook for files/folder dialogs;
- It was get rid of extra 'default' material replication;
- Fixed the missing '*' for unsaved status after a file be merged.

Fixes to v2.0.5 (c)

---

src/wings_dialog.erl
src/wings_frame.erl
src/wings_pref.erl
src/wings_render.erl
src/wings_view.erl

It was added preview capability to the Camera dialog. The Image Plane preview
is shown on the Geometry window as a blue border. It also can be activated by
enabling it using the proper option in View->Show menu.
Note: Added a Camera settings preview. Thanks tkbd for the suggestion.

Added preview resource to Camera dialog

---

plugins_src/import_export/wpc_pov.erl

The changes were built to explore new resources available in the current version of POV-Ray: 3.7.
Thanks to oort and tkbd for test them.
- Added support to Environment lights (Gradient, HDRI, SkyDome and SkyBox) to
be set in Ambient light;
- Added new material finish parameters Phong, Irradiance and Translucency (for SSLT);
- Added render option to define the number of threads to be created;
- Added render option to create transparent background;
- Added POV-Ray's presets for render quality;
- Organized the Render options dialog moving the AA settings to the "General
Options" tab and moved the Radiosity settings to a new "Lightning" tab;
- Added option to choose between the two AA methods available in POV-Ray;
- Added render option to enable and set SSLT parameters.
- Fixed the angular …

Improvements to POV-Ray plugin

---

plugins_src/import_export/wpc_kerky.erl
plugins_src/import_export/wpc_pov.erl
src/wings_plugin.erl
src/wings_view.erl

Only the event: "The pattern 'edit' can never match the type 'render'" was
no fixed because it must be used but, for that, the wings_plugin module
needs a fix that will remove/add the menu items.
In the current implementation if we disable any render plugin and try to
access the Plugin Preferences dialog we get a crash.

Fixed the not used statement pointed by dialyzer

---

plugins_src/commands/wpc_sel_win.erl
plugins_src/commands/wpc_views_win.erl
src/wings_plugin.erl

The issue was observed when disabling a plugin with window docked and after
left and start/restating Wings3D we got a hard crash that denied Wings3d to
be started. The way to fix that was only by editing the preferences.txt.

Fix the crash when disabling a plugin which has a window docked

---

plugins_src/commands/wpc_region.erl

Apparently this bug kept hidden since the wings_drag code review.

Fixed crash caused by wrong parameter type in Rotate->Region

---

intl_tools/tools.erl
intl_tools/wings_intl.hrl

It is no longer necessary for the parse transform to insert the
function name into the key tuple, because it can be handled by
the ?FUNCTION_NAME macro introduced in OTP 19. We will continue
to use the parse transform to check for errors (such as duplicated
keys), but it can be simplified.

Simplify the parse transform for internationalization

---

plugins_src/import_export/wpc_ps.erl

Besides the crash that was reported previously, the plugin was not managing
correctly the file data with multiples objects definition. Some creators use
to fill the boundary data and others not. The code used from wpc_tt.erl module
needs that information in the right way, so I tried to prepare/repare the data
before call that module. We try avoid to load the boundary data since it results
in a big box object on screen. It was tried to avoid Wings3D crashes, se there
are some code to enable that and I also included more feedbacks to the user.
NOTE: Fixed PS/EPS importer which was not importing files properly.
It should import Adobe Illustrator, LibreOffice and Inkscape files correctly.
Scribus file may not to have some objects loaded. Thanks to tkbd for all support.

Fixed PS/EPS importer which was not importing most the user's file

---

src/wings_u.erl

The intention is to get some extra information from the user since most the time they don't provide us (without ask for) and it can be relevant in some circumstances.
It will look like this
> Dump written 2017-2-16_11-41
> Version: 2.1.5.154.g423ed
> **OS: Windows 7 (build 7601, Service Pack 1), 64-bit edition
> GPU: Intel | Intel(R) HD Graphics**
> Window: geom
> Reason: function_clause
> ...

Added the OS and GPU information to the crash dump file.

---

plugins_src/commands/wpc_absolute_move.erl

If duplicates were chosen, there would be twice as many duplicates
created than requested. The bug was introduced in eef76b3a18032c64.

Fix excessive duplication of objects in Absolute Move

---

src/wings.erl
src/wings_render.erl

It was noticed the redraw function in auto rotate code was not calling
an user defined draw hook (via register_postdraw_hook)
As the wings_render:render/1 is called from wings.erl, wings_tweak.erl and
wings_view.erl I believe the best option would be move that call to the
render module since it is always called just after render/1 be called.

[Option 2] Fixed the missing call to post hook in auto rotate mode

---

src/wings_face_cmd.erl

NOTE: Fixed the crash in Put On command (LMB option) when no destination was
selected. Thanks to Hank.

Fixed crash in Put On command (LMB option)

---

src/wings_obj.erl

By default the object's pst doesn't have the ?FOLDERS key added and the
use of gb_trees:update/3 was causing the crash since it requires the key
to exists.
NOTE: Moving any object to a folder was causing a crash. Thanks to Hank.

Moving objcts to a folder was crashing Wings3D

---

src/wings_obj.erl

NOTE: Fixed a issue which was allowing locked objects be moved if them
were previously selected. Thanks to OXO.

User was able to move locked objects if them were selected before.

---

src/wings_render.erl
src/wings_view.erl

The option to show the 'Camera Image Plane' was causing Wings3D to crash.

Fixed the render code for 'View->Show->Image Plane'

---

plugins_src/import_export/wpc_gltf.erl

- fixed the wrong jpeg file extension which is '.jpg';
- fixed the invalied "Invalid accessor format '{VEC2_FLIP_Y, FLOAT}'"
that is cause by the VEC2_FLIP_Y no be recognized by glTF parser.
Since the Y coordinate for textures must be always inverted that was
made in the code.

Fixed some issues in the glTF exporter

---

src/wings_color.erl
src/wings_va.erl
src/wings_we.erl
src/wings_we_build.erl

Changed the wings_we:build/2 to handle a #e3d_mesh{} that contains vertex
color information present in some imported files.
The '.obj' format doesn't supports vertex color natively, but others like
'.ply' and '.glTF' does.

Added support to vertex colors when importing files

---

src/wings_vertex_cmd.erl

That was caused by the recents code updated wich now translate_fun is now has
a type definition that is requiring e3d_vec:vector() as paremeter. For the
situation like that we where passing a empty list as parameter.

Bevel command was craaching when a vertex which dived a edge

---

plugins_src/autouv/wpc_autouv.erl

It was asked by the user OXO to make possible to continue the UVmapping in
the same monitor (for multiple monitors setup) and that uses to be really 
annoying. This way, if the user start to segmenting the mesh in another monitor 
than the  one in which the main window is, the next AutoUV window will be 
displayed in the same monitor.
NOTE: UV mapping windows are displayed in the same monitor as the first one 
was placed. Thanks OXO.

AutoUV window been shown in the same display as the segmenting window is

---

plugins_src/import_export/wpc_gltf.erl

It was noticed during some test using the projects provided by Chronos
that some files may have integer values instead of the float ones as
expected by the importer.

Fixed an crash caused by no float value imported

---

src/wings_draw_setup.erl

It was provided a model by Hank in which after evaluation was found a face
with five vertex, but no area. That was resulting in a zero lenght normal.
The change is intended to avoid Wings3D get a hard crash by a user fault.
NOTE: Fixed hard crash caused by malformed faces. Thanks Hank.

Fixed hard crash caused by malformed faces

---

plugins_src/import_export/wpc_hlines.erl

It was noticed after the latest changes to material setting that the plugin
was wrongly using ambient from material settings to set the material as
transparent.
NOTE: Fixed the EPS/SVG plugin exporting back edges. Thanks to tkbd.

The EPS/SVG plugin was exporting back edges

---

src/wings_drag.erl
src/wings_vertex_cmd.erl

The problem was affecting only the Tighten command for the AutoUV window and
it was related to an empty list of vertex passed to drag module.
As I could check, it was introduced after the changes made to wings_drag module
in versin 2.1.6.
NOTE: Fixed the crash caused by Tighten in AutoUV window. Thanks to Hank.

Fixed the crash caused by Tighten in AutoUV window

---

src/wings_view.erl

When jumping to a saved view during a vector input operation and the
current saved view was the same as the current one, the code was returning
a 'keep' value instead of the non changed #st{} - which was the expected
value by the wings_vec module.
Reported here: http://www.wings3d.com/forum/showthread.php?tid=2749
NOTE: Changing to a saved view in the middle of a vector input operation
was causing Wings3D to crash. Thanks to Hank.

Fixed a crash caused by wings_view during vectors input

---

src/wings_material.erl

Reported here: http://www.wings3d.com/forum/showthread.php?tid=2754
NOTE: Wings3D was crashing when a material was selected by using it's color
icon. Thanks to Hank.

Selection of a material by hitting the color icon was causing a crash

---

plugins_src/import_export/wpc_gltf.erl

There were still chances of a integer values be found in the material
definition instead of a float.
Reported here: http://www.wings3d.com/forum/showthread.php?tid=2757
NOTE: Importing a .gbl project was causing a crash just before it to be
displayed. Thanks to tkbd.

Fixed a drawing crash caused by wrong value imported by glTF module

---

src/wings.erl

Made Wings3D to understand correctly the file extension.

Wings3D was not accepting drop a file with a uppercase extension

---

src/wings_ff_wings.erl
src/wings_sel.erl

The selection validation shoud not to ignore hidden/locked object when
we are saving them to Wings3d file. As it's a special case I created a
new function to handle that.
Reported here: http://www.wings3d.com/forum/showthread.php?tid=2756
NOTE: Selection groups has not been saved for hidden/locked objects.
Thanks to Hank.

Selection groups has not been saved for hidden/locked objects

---

plugins_src/accel/wpc_pick.erl
src/wings_pick.erl

That is another asleep bug, present since 2.0
Reported here: http://www.wings3d.com/forum/showthread.php?tid=2758
NOTE: If a area light is present only the faces facing the camera can get
selected by marquee selection. Thanks Hank.

Fixed the marque selection when an area light was present (face mode)

---

src/wings_frame.erl

It was obseved a crash in wings_frame module when handling the #wxClose event
which was unexpected and means an unhandled #wx{obj} is firing this event.
As a workaroound we are going to check for that and display some information
that would help us to know what is that object and how to permanently to fix
the crash cause.
Reported here: http://www.wings3d.com/forum/showthread.php?tid=2733
NOTE: Wings3D was crashing unexpected in module wings_frame. It was add a
workaround and some information to help us to find the cause. Thanks to  Hank

Workaround to a hard crash when closing a non registere window

---

plugins_src/import_export/wpc_yafaray.erl

The default value (true) was causing the background to not be rendered.
In accord with oort that setting can render right only with Yafaray versions
prior to E1.0.0.
To avoid users to get the render issue newest versions we decided to set its
default value to 'false'.

Changed default setting for 'Transp Refraction' to 'false'

---

plugins_src/commands/Makefile
plugins_src/commands/wpc_isometric_view.erl

It will not reset the current view, but just adjust the camera location and
mode (Orthogonal) and it will be applied for the current geometry window (in
case we use a layout with others than the default one).
This plugin is intended to help modelers to see how their project will looks
like in games which uses the Isometric view.
It was a need by the user SiriusCG which we needed to trick Wings3D to be
able to reach the expected effect.

Plugin that add a Isometric view option

---

src/wings_material.erl

Bug reported here: http://www.wings3d.com/forum/showthread.php?tid=2789
NOTE: Select by Material in Outliner window was not working in accord when in
body selection mode. Thanks Hank.

Fixed wrong behaviour when using Material->Select option

---

src/wings_body.erl

The option was not available in the context menu in body selection
mode as we have for all other lights.

Fixed the missing option to Edit light area property

---

src/wings.erl
src/wings_frame.erl
src/wings_status.erl
src/wings_theme.erl

The Information Line was not using the customization settings and the
Active/Inactive window titles was not getting its text color updated
on-the-fly as the background was.
The titles uses a panel with a staticText for the caption which needs
to have its foreground color set.
obs: the bar still requires Wings3D to be restarted to get the color applied.

The UI color customization was not working properlly

---

src/wings_menu.erl
src/wings_pref.erl

Preferences subset was get a crash when we try to save a new one.
It looks like we broke it when switching from SDL to wxWidget library.
The code is very similar to the one for Recent Files, but cannot be the same.

Fixed the option to Save preferences subset

---

src/wings_wm.erl

It was already added support to plugins manage its "own" geometry window
in the function geom_below/1. This is also an important complementation.

Added missing info about geometry window to plugins

---

plugins_src/import_export/wpc_hlines.erl

NOTE: Error exporting .eps/.svg files using diacritical marks. Thanks Hank

Fixed an error in eps/svg exporter

---

src/wings_dialog.erl

- Dialogs using notebook controls (oframe) were causing Wings3D to crash when
we try to get the default values when dialogs should not be shown.
It was noticed that option was not implemented, so this is a fix for it.

Fixed a crash in dialogs with notebook tabs

---

plugins_src/import_export/wpc_jscad.erl

- The first version was splitting the object by default and it seems to not be
the right thing to do. So, it was added the "One group per material" option
to the dialog;
- Each object is created in a function named with its name and in case of the
previous option be checked, then it will include the material name too; That
will allow uses to create primitives on Wings3D and use it on their scripts
to create multiples copies of it;
- Added the option "Export faces group" to export the groups number (based on
material), but without split an object in multiple ones;
- Added the option "Creation function returns" ("GSG Object" or "Properties");
- Added the option "Build the main() statement" that will allow the exported
file be part of a library and be used as includes;
NOTE: The JSCAD plugin …

JSCAD plugin rewritten to offer more flexibility

---

src/wings_menu.erl

This fix the mouse release error message we get on Erlang console, although
the error isn't displayed in the compiled version of Wings3D. I noticed it
only when the context menus were opened and a new App get focused.
Maybe it would be maybe generated by not processing the window event
wxMouseCaptureLostEvent.
Ref.: https://docs.wxwidgets.org/trunk/classwx_mouse_capture_lost_event.html
These are the messages now skipped:
wx: error
message: wxWidgets Assert failure: ..\..\src\common\wincmn.cpp(3300):
"Assert failure" in wxWindowBase::ReleaseMouse() : Releasing mouse in
00000000100415F0(wxWindow) but it is not captured
wx: error
message: wxWidgets Assert failure: ..\..\src\common\wincmn.cpp(3319):
"!wxMouseCapture::stack.empty()" in wxWindowBase::ReleaseMouse() : Releasing
mouse capture but …

Fix the mouse release error message

---

plugins_src/import_export/wpc_jscad.erl

It was noticed that it be an important option since some scripts made
for OpenJSCAD may require triangles only.
NOTE: Added the Tessellation option to the jscad exporter. Thanks gilboonet

Added the missing tesselation option to the jscad exporter dialog

---

src/wings_image.erl
src/wings_wm.erl

The screenshot command was always getting the image size from the main geometry
window (by considering a layout with multiple ones)- wings_wm:this() was always
referencing 'geom' window. But the copied buffer was the last one drawn (maybe).
To ensure we were copying the proper one it was added a new function to
wings_wm to allow us require a specific geometry window to be drawn and then
we can access the correct OpenGL buffer.
When a detached geometry window is active it loses the focus when we use the
main menu. So, in this case the main geometry window will be used for capture.
It was also removed the option to capture the entire window since it was not
working well since we started to use the wx library (requested by Dan).
NOTE: Fixed the screenshot command which was only capturing the …

Fixed bad behaviour of screenshot option

---

plugins_src/autouv/shaders/hexagon.fs

It was noticed that option for "Pineapple Fruits style" was not working for
long time. There were some missing coeficient since a review made in the
opacity property.
NOTE: Hexagon in texture shader was broken. Thanks to tkbd

Fixed the Hexagon texture shader which was not working

---

src/wings_drag.erl

The mouse wheel event was introduced in this **maint** branch and will be available in the next release. I found a bug in _wings_drag.erl_ which was not prepared to handle it.

Fixed a missing update to wings_drag in order to handle #mousewheel{} event

---

src/wings_wm.erl

**I'm not sure this fix was mad in the appropriated way**, but it was needed in order to ensure the
wm_focus data used in wings_wm:message_event(redraw) get the correct focused
window instead of 'undefined' and this way the status bar can be updated.
NOTE: The right message used to show extra information to the user actions
was missing with the previous message kept static. Thanks to Sevendy3

Fixed the missing right message in the information line

---

plugins_src/import_export/wpc_wrl.erl

Fixed wrong material setting after the material changes intruduced due new
PBR render.
After the material changes the ambient color property is set to
{0.0,0.0,0.0,1.0} and was causing the exported values ambientIntensity and
transparency to be inverted causing object to not be shown;
To minimize any impact of any older project being opened in a previous version
of Wings3D it was only checked it the ambient valuer is zero. In this case we
assume we have to fixe these properties.
From: http://gun.teipir.gr/VRML-amgem/spec/part1/nodesRef.html#Material
- The ambientIntensity field specifies how much ambient light from light sources
this surface should reflect. Ambient light is omni-directional and depends
only on the number of light sources, not their positions with respect to the
surface. …

WRML plugin was exporting wrong material settings

---

c_src/Makefile

That will enable me to keep building Wings3D from only one dev environment and should not bring any problems to other dev environments.
* @dgud, we already talked about this before by email (in June).

Fixed a build error when making libigl in msys2 environment.

---

src/wings_sel_cmd.erl

NOTE: It was noticed there was a missing option for Select menu that
allow us to lock the current selected objects. Thanks to tkbd.

Added the missing option Lock Selected

---

plugins_src/autouv/wpc_autouv.erl

NOTE: Alignment commands not valid for Body or Face mode was causing the AutoUV
window to crash when a repeat command was used in these modes.

Fixed repeat command in AutoUV window

---

src/wings_util.erl

It was noticed collada may generate files with NaN for float numbers. As
checked, others 3D apps use to automatically to convert them to 0.0, so
it was changed the wings_util:string_to_float/1 in order to fix that.
This will prevent any other importer to break Wings3D in the future.
NOTE: Fixed the collada inporter error caused by NaN values. Thanks to tkbd

Fixed collada importer error

---

src/wings_sel_cmd.erl

NOTE: Run the Select->Similar command in an empty was causing Wings3D to
display the 'Delete Hotkey' dialog.

Fixed select similar command for an empty scene

---

src/wings_dialog.erl

It was reported that any of the windows opened from the Help option becomes
hidden by the main window as soon as the mouse lay over the geometry window.
This behaviour started in v2.2.5 after the inclusion of a call to
update_focus/1 in wings_wm:grab_focus/1 (https://github.com/dgud/wings/commit/234f62338a1c8afdd6fb976f1a37247b0099ee1f#diff-8a2f0ce40501e1138f9babada3f5e4a4R458)
In order to make it have the old behaviour (keep visible over the main window)
we need to add the stay on top flag to the wxFrame style.
NOTE: Fixed the help windows visibility which were getting hidden when moving
the mouse outside it. Thanks Grumbler.

Fixed the help windows being hidden by geometry grabing focus

---

src/wings_dissolve.erl

It was noticed that by using commands like 'Select Similar Normals' the
faces marked as hole was also selected and by dissolving the selection
the #we{}.holes was not updated to remove these faces.
It was opted to keep the holes or hidden faces select since for some commands
it can be of interest move these faces too. This is noticeable with hidden
faces when becoming visible will be close to the ones moved previously.

Fixed crash caused by garbage left when dissolving faces

---

plugins_src/commands/wpc_sel_win.erl
src/wings_body.erl
src/wings_dialog.erl
src/wings_material.erl
src/wings_outliner.erl
src/wings_sel_cmd.erl
src/wings_view.erl

It was also needed to fix the wings_dialogs.erl in order to fix the text
control which was not taking correctly in account the 'width' flag.
NOTE: Input dialogs to name/rename elements now is a little wider. Thanks tkbd
for the suggestion.

Changed the renaming dialogs to show a wider input name

---

plugins_src/import_export/wpc_stl.erl

It was added a simplified export dialog including the option for scale
and subdivide the scene. It was also added a drop down list for unit
conversion (1WU to 1STL/1mm/1cm/1inch), the conversion scale and
the object scale.
The combination of the first two generates the value for the conversion
scale which multiplied by the object scale results in a update for the
'Export scale' text box.
There are some information about a list of some knowing slicer 
softwares we tested and checked that 1 STL unit is converted to 1mm.
That should help the users to understand its relationship with the 
Wings3D unit (1WU = 1STL unit)
NOTE: Added a dialog to STL exporter allowing users to set the scale.
Thanks to dawntreader, imagine and Mert HANCIOGLU(instagram) for provide
us information about the slicers …

Added a dialog to STL exporter

---

plugins_src/autouv/auv_texture.erl
plugins_src/autouv/wpc_autouv.erl

During the previous commits to add the shader preview feature we started to get
and crash when an mirrored object was in use. Initially, the problem seemed to
be related to the new changes, but in fact it was sleeping. It started after a
fix that allow us to work with images in shaders, which now we can make use of
require 'normals' information.
So, the fix was just "tell" wings_we:normals/3 there is no mirror in the object
when we request it to compute the normals we need.
I noticed I did a mistake in draw_options/1 by requesting the current #st{} to
use in the dialog preview returns, as well as get_texture/2 required the AutoUV
It was also rearranged the AutoUV menu items in order to keep the Create Texture
on the menu bottom - as it used to be. This way the menu still is comfortable to …

Fixed shader preview crash for mirrored objects

---

src/wings_face_cmd.erl

The problem was sleeping, since it was construct in a wrong way by using the
selection state #st{} when the menu face was invoked. Changed it to get the
current #st{} when user choose the command.
NOTE:
- Lift command with LMB option was not working properly due the use of the
selection state when it first was used. Thanks Hank for report it.

Fixed Lift command for LMB option

---

plugins_src/autouv/wpc_autouv.erl

It's common we need to rearrange the UV islands aligned by top/left/right or
bottom. Currently, we need to use 'Move To' in order to align them to the
UV boundaries and then move back to a desired position.
NOTE:
- Added Align option to AutoUV in order to make easier to align islands to each
other.

Added align option to AutoUV window

---

plugins_src/autouv/shaders/Makefile
plugins_src/autouv/shaders/image_mixer.fs
plugins_src/autouv/shaders/triplanar.fs
plugins_src/autouv/shaders/triplanar.vs
plugins_src/autouv/shaders/triplanar3.fs
plugins_src/autouv/shaders/wpc_image_mixer.auv
plugins_src/autouv/shaders/wpc_tile.auv
plugins_src/autouv/shaders/wpc_triplanar.auv
plugins_src/autouv/shaders/wpc_triplanar3.auv

- Added triplanar shaders for one image and three images as input;
- New image mix shader which allow us to blend an image with the previous layer;
It requires the updates made to auv_texture module (420f822) - already approved
in order to be able to load images on Option dialog.
Note:
- Added triplanar and image mix shaders to AutoUV shaders.

Added new shader options

---

plugins_src/autouv/auv_texture.erl
plugins_src/autouv/shaders/wpc_edgefilter.auv
plugins_src/autouv/shaders/wpc_filter.auv

It was added a new paramter to the wpc_***.auv that let the code know it
doesn't requires/produce a texture preview.
It was also made some changes to prevent crashes if a shader settings previously
stored in the preferences and load in a new project references an image that is
no long available or a shader that was removed. In these situations the stored
information is removed from the layer/slot before the Options dialog be shown.

Added option to avoid shaders to use the preview sphere in dialog

---

src/wings_shaders.erl

This workaround prevent the bad quality on PBR material for some Intel graphic
drivers. In a mirror object the image may be too blurred.

Fixed an issue with PBR material on Intel graphic driver

---

plugins_src/import_export/wpc_yafaray.erl

After the previous inclusion of this information in the plugin, it was noticed
the visibility property doesn't applies to the light portal material. So, it is
now disabled for that kind in order to avoid user misunderstanding.

Fixed the behaviour of visibility field for Yafaray

---

src/wings_render.erl
src/wings_view.erl

- Decreased the near clipping value from 0.01 to 0.001;
This limitation has been commented time to time. I already experienced that
sometimes. So, by changing it we open the possibility to work correctly with
detailed object which has small pieces that need attention.
- Added the possibility to draw the ground grid for scales 0.1, 0.01 and 0.001;
The grid for these scales was missing.
- Adjusted the function bind for drawing the main axes. The exact 0.0 value
barely is reached and sometimes they are hidden by the grid line. That can 
be noticed on the attached image.
NOTE:
- Decreased the near clipping value from 0.01 to 0.001;
- The ground grid is also now drawn for scales as 0.1, 0.01 and 0.001;

Small adjustments to the geometry visualisation

---

src/wings_material.erl

When working with many material it would be faster just select a piece of
the object and pick the material to be edited. The MMB option added to
the Material menu option in Face mode will allow this by complementing the
other options: Create and Assign;
NOTE:
- Added MMB option to Material menu item when Geometry window is in Face
selection mode. Thanks Hank for the suggestion.

Added MMB option to Material menu option in Face mode

---

plugins_src/import_export/wpc_yafaray.erl

It was missed the ending tag of lightportal data in the export section.
NOTE:
- Small fixes to Yafaray plugin. Thanks to oort.

Fixed the lightportal section in the exporter.

---

plugins_src/import_export/wpc_yafaray.erl

NOTE: Fixed the remaining non-latin characters handling in order to prevent
further crashes in Yafaray exporter. Thanks to tkbd.

Fixed Yafaray file exported with non-latin characters

---

src/wings_image.erl

Sometimes when the image list has an image with name is 'none' Wings3D is going
to hard crash. That was introduced in the current version when it was tried to
improve the evaluation for an already loaded image.
NOTE: Fixed a crash caused by checking image name. Thanks to rgcotl (at Discord)

Fixed a crash caused by checking image name

---

plugins_src/import_export/wpc_kerky.erl
plugins_src/import_export/wpc_pov.erl
plugins_src/import_export/wpc_yafaray.erl
src/wings_material.erl
src/wings_plugin.erl

The change was made to speed up the access to the Material dialog which
became too slow since the UI was migrated to use wx library.
When an user choose a render plugin to change its setting that will be
assumed as his/her preferred render engine (which usually is). So, in the
next time the material dialog be accessed it will automatically set to
use that one.
p.s.: I tried to minimise the changes and keep the material data consistent with
any Wings3D version.
NOTE: The material properties for plugins are now accessed by choosing the
plugin name in a drop-down list and clicking on the "Edit..." button.

Moved the material properties for plugins to another window

---

src/wings_material.erl

Fixing the missing verification for when no render plugin was still set and its dialog mode is Automatic.  (happens to new users)

Fixed a error introduced with the changes to material dialog.

---

src/wpa.erl

NOTE: Drag and drop file feature was not importing files with uppercased file
extension. Thanks to rgcotl at Discord.

Fixed a drag and drop file issue

---

src/wings_frame.erl
src/wings_menu.erl

NOTE: Fixed marquee transparency on Linux. Thanks to Klim.

Fixed marquee transparency on Linux

---

src/wings_edge_cmd.erl

I noticed a soft crash when I selected only one edge in the entire scene and
choose the Connect command [RMB] switching from Percent to the Absolute [1]
option.
In that situation the MinUp and MinDown in Units parameter for wings_drag have
the 'unknown' value.
```
Long stack trace:
[{erlang,'-',[unknown],[{error_info,#{module => erl_erts_errors}}]},
{wings_edge_cmd,slide_units,3,[{file,"wings_edge_cmd.erl"},{line,444}]},
{wings_edge_cmd,slide,1,[{file,"wings_edge_cmd.erl"},{line,409}]},
{wings_develop,time_command,2,[{file,"wings_develop.erl"},{line,87}]},
{wings,raw_command,4,[{file,"wings.erl"},{line,643}]},
{wings_wm,handle_event,3,[{file,"wings_wm.erl"},{line,1039}]},
{wings_wm,send_event,2,[{file,"wings_wm.erl"},{line,1005}]}, …
```

Fixed a soft crash when using Connect RMB (Absolute option)

---

plugins_src/autouv/wpc_autouv.erl

It was noticed the Align command was not working properly. For some reason I missed something during the tests and it was almost unusable.
NOTE: Fixed Align command in AutoUV editor that was not working properly.

Fixed Align command in AutoUV editor

---

src/wings_dialog.erl

I've already noticed that before, but always forget about to check from where it was coming. When a crash was happening in a dialog call the catch process sometimes was trying to pop an unexistent pararent window from the stack. That was causing another crash which the message was shown on the console:
```
Reason: {{badmatch,[]},
[{wings_dialog,reset_dialog_parent,1,
[{file,"wings_dialog.erl"},{line,435}]},
{wings_dialog,'-build_dialog/3-fun-0-',3,
[{file,"wings_dialog.erl"},{line,887}]},
{wx,batch,1,[{file,"wx.erl"},{line,201}]},
{wings_dialog,dialog_1,5,[{file,"wings_dialog.erl"},{line,267}]},
{wings_wm,handle_event,3,[{file,"wings_wm.erl"},{line,1039}]},
{wings_wm,send_event,2,[{file,"wings_wm.erl"},{line,1006}]},
{wings_wm,do_dispatch,2,[{file,"wings_wm.erl"},{line,898}]}, …
```

Fixed an issue that was masking real error messages for a while

---

src/wings_menu.erl

It was noticed the context menus has stopped to be shown close the mouse on a multiple display setup. This issue was workaround in the past in PR#392. But, it seems wxWidgets has fixed the issue with the mouse location in this kind of setup bring back this kind of issue.
NOTE: Fixed misplaced context menu in a multiple display setup.

Making context menu always fits inside the display

---

src/wings_io_wx.erl
src/wings_menu.erl

As an advice for us, we should preferer to use wx_misc:getMousePosition() if we need only the mouse coordinates 
instead of wings_io:get_mouse_state() to get the mouse coordinates.

Fix and workaround related to mouse coordinate in multiple display setup

---

plugins_src/import_export/wpc_svg_path.erl

Additions and fixes to the SVG path plugin.
Changes include:
* New path tokenizer
* Handling of more path commands (H V Q S T A h v q s t a)
* XML parsing with xmerl
* More SVG elements handled (less need for the user to convert objects to path before saving)
* Scaling calculated from document size and viewbox to match the scaling of EPS/PS and AI importers.
* Fixed relative positioning of sub-paths
* Added clipped mask textures
* Added path fill color to mesh

SVG plugin additions

---

src/wings_image.erl

The screenshot name was get into a list which was causing the wings_dialog to brach when building the text control.
NOTE: Fixed a crach when renaming screenshots. Thanks to markie.

Fixed a bug in internal screenshot naming

---

src/wings_edge_cmd.erl

It was noticed if we have only one edge selected and the Connect RMB command is activated the it was entering in slide mode even without a valid edge to move. That could trick the user.
NOTE: Fixed the Connect RMB command that was entering in slide mode after no connection has been done.

Fixed an issue to Connect RMB option when only one edge was selected

---

plugins_src/autouv/wpc_autouv.erl

This command help us to fix issues on textures after we have UV mapped an object and execute any command like Extrude, Slide, Bevel, ... which doesn't updates the object's UV information.
[Video demonstration](https://youtu.be/VKJqyf7bT3E)
NOTE: Added Proportional option to the Distribution command in AutoUV editor.

New command Proportional Distribution added to the  AutoUV editor

---

plugins_src/commands/Makefile
plugins_src/commands/wpc_align_to_axis.erl

This plugin allow us to rotate and orient an object directly to an axis or a vector by using a reference vector.
There are three options available. Two to align to default system axis and one to align to an arbitrary vector:

New command plugin to align an object to axis/vector

---

plugins_src/commands/wpc_flow_connect.erl

It was noticed that Flow Connect command was causing a soft crash if we select it by using the MMB - which doesn't has any action assigned.
```
Long stack trace:
[{wings_menu,make_entries,
[[flow_connect,edge],{edge,flow_connect},pretty],
[{file,"wings_menu.erl"},{line,970}]},
{wings_menu,wx_popup_menu,6,[{file,"wings_menu.erl"},{line,179}]},
```
NOTE: Fixed a soft crash caused by selectiong MMB for Flow Connect command

Fixed a soft crash caused by selectiong MMB for Flow Connect command

---

src/wings_gl.erl

That is not clear if it's a GPU driver or wxWidgets issue. After a couple of tests playing around with the 'Intel Graphics Control Panel' settings I found out the issue was caused by the MSAA setting. By switching it from 'Turn Off' to 'Use Application Settings' fixed the problem.
Because it seems MSAA is turned off by default in some systems and because it's hard to the user to figure out it's causing the Wings3D failing to start, I'm proposing a validation. Since now we have a way to check if wxGLCanvas can support some attribute (in Erlang 25.3) we can  test for it before create a wxGLContext and eventually start Wings3D with MSAA feature disabled.
NOTE: This fix a hard crash on starting Wings3D related to MSAA disabled in a PC setup which the main GPU is an Intel.

Disabling MSAA feature in case of hard crash on Wings3D start

---

plugins_src/import_export/wpc_svg_path.erl

I fixed the paths_round_rect function (used by &lt;circle&gt;, &lt;ellipse&gt; and &lt;rect&gt;) so it doesn't generate repeat coordinates which causes different problems such as either key_exists errors, or a broken mesh in some cases. The bug was found when shapes made with the <circle> tag when the "combine all paths" option is used and another circle is inside will cause a broken mesh (thank you tkbd for the bug report). Also fixed the tokenizer when the characters "e-" is encountered. Also, the importer will try a second time on a shape that got the "key_exists" error by removing points whose coordinates are too close to adjacent points, this has been tested and works for paths where it looks like "key_exists" is caused by coordinates being repeated or being too close together.
NOTE: …

wpc_svg_path: circle tag using combine all paths fix

---

plugins_src/import_export/wpc_svg_path.erl

Fixed the x11color argument, I'm not sure how I missed this.
NOTE: Fixed x11color argument of wpc_svg_path.

wpc_svg_path: Fixed x11color argument.

---

plugins_src/import_export/x3d_import.erl

NOTE: Added a fix for when a wrl/x3d file has an IndexedFaceSet with a texCoord but doesn't have a texCoordIndex specified. Thanks tkbd for finding the bug.

x3d_import: Fix for IndexedFaceSet with texCoord but not texCoordIndex

---

shaders/background.fs
shaders/lib_envlight.glsl
src/wings_light.erl
src/wings_shaders.erl
src/wings_view_win.erl

It's a missing option (in my opinion) since mostly 3D apps which works with
PBR visualisation allow us to rotate the environment map around the static
object to give us the possibility to evaluate how the object is lit by
different angles.
NOTE: Added option to rotate the environment map.

Added option to rotate the environment map

---

src/wings_hotkey.erl

There are a couple of default hotkey set to use DELETE key. So, it was allowed to use it to be bind to any command, as well as INSERT, but taking care about the combination with CTRL which are used to invoke bind/unbind commands.
NOTE:
Fixed the bind DELETE key after it has been unbound. Thanks to ptoing.

Fixed the impossibility to bind DELETE key after it has been unbound

---

src/Makefile
src/wings_color.erl
src/wings_palette.erl
src/wings_palette_imports.erl

Two features and fixes for the palette window:
* Import and export to various palette formats.
* Right mouse click on an area of the palette without a palette entry now shows a menu.
New Imports:
* From swatch image: imports from images containing solid color squares, often generated from color palette web sites.
* Adobe Palette: imports from various adobe palette types.
* From text file: detects hex color codes, CSS style rgb(...) and tabular RGB data
* Sample from image/texture: Samples the most common colors from any file or imported texture.
New Exports:
* SVG/EPS swatch: exports swatch-style images in SVG or EPS format
* Text file: exports hex color code and column based text files
* SVG/TeX+TikZ legend: exports a labelled list of colors in SVG or TeX+TikZ.
Thanks tkbd and micheus …

New features and fixes to palette window

---

plugins_src/import_export/wpc_gltf.erl

- Fixed the file type in dialog for exporting glTF;
- Initialized the file name to be exported with the project name.
NOTE:
The file type in the file dialog now is in accordance with the glTF type
chosen in the option dialog. Thanks to markie

Fixed the file type in dialog for exporting glTF

---

plugins_src/autouv/wpc_autouv.erl

It was missing the message error for edge mode in order to avoid a wrong number of edges selected in one chart.
NOTE: Fixed a crach in autouv when rotating a char with multiple edges selected.

Fixed a crach in autouv when rotating a chart

---

plugins_src/autouv/wpc_autouv.erl
plugins_src/commands/wpc_bend.erl

The bend command can help us to make curved islands become straight.
NOTE: Added Bend command to AutoUV toolset.

Added Bend command to AutoUV toolset

---

e3d/Makefile
plugins_src/autouv/Makefile
plugins_src/commands/Makefile
plugins_src/import_export/Makefile
src/Makefile

In OTP 26.1, matching with 0.0 will produce a warning. For the moment, suppress the warning.

Suppress warnings for matching with 0.0

---

plugins_src/commands/Makefile
plugins_src/commands/wpc_duplicate_radial.erl

This command intends to make easy the duplication of objects that need to be placed in a circular or spiral arrangement.
[![Duplicate_Radial_-_X.png](https://i.postimg.cc/VJGmDf2L/Duplicate_Radial_-_X.png)](https://postimg.cc/VJGmDf2L)
[![Duplicate_Radial_-_Y_-_shift_on_axis.png](https://i.postimg.cc/B8Rsfhqr/Duplicate_Radial_-_Y_-_shift_on_axis.png)](https://postimg.cc/B8Rsfhqr)
[![Radial_Duplicator_-_Pick.png](https://i.postimg.cc/cKvZjqN7/Radial_Duplicator_-_Pick.png)](https://postimg.cc/cKvZjqN7)
NOTE: New Duplicate Radial command.

New Duplicate Radial command

---

plugins_src/import_export/x3d_import.erl

I've fixed a bug of for the transparency. Thank you for the bug report Xavier on the wings forum.
I've also added gzip support.

x3d_import: Fixed transparency, added gzip support

---

plugins_src/import_export/wpc_yafaray.erl

Without the change, I got this warning (and thus build error):
```
erlc +nowarn_match_float_zero -Werror -pa ../../intl_tools -I ../../..  +debug_info -o../../plugins/import_export wpc_yafaray.erl
compile: warnings being treated as errors
wpc_yafaray.erl:4011:41: adjacent string literals without intervening white space
In OTP-27.0 this will be a triple-quoted string or an error.
Rewrite them as one string, or insert white space
between the strings.
% 4011|     uniprintln(F, "  <material1 sval=\"""w_""\~ts\"/>~n"
%     |                                         ^
wpc_yafaray.erl:4011:45: adjacent string literals without intervening white space
In OTP-27.0 this will be a triple-quoted string or an error.
Rewrite them as one string, or insert white space
between the strings.
% 4011| …
```

Fix triple quote warning

---

plugins_src/autouv/wpc_autouv.erl

It was added some missing options to the context menu in AutoUV as well as an option to 
tile the texture which can be useful for some projects (like for games).
NOTE:
New options added to AutoUV:
- Added the options Center, Center X and Center Y to the Align command;
- Added the RMB option to Scale command to choose a reference point;
- Added the RMB option to Rotate command to choose a reference point;
- Added option to show the background texture in tiled mode.

New additions to AutoUV menus

---

plugins_src/import_export/x_import.erl

Fix: Removed code that made all edges hard. Now lets imported normals be used to determine hard edges.

X importer hard edges fix

---

src/wings_menu.erl

OBS: There are two fix on this PR because the second one was causing conflict if it was separated.
**1**) This issue was added when I remove a old workaround for multiple display
setup and didn't pay attention that it was also making the menu window
to fit on a display. I revert the commit and rewrote it.
It's not perfect for setups where the displays have different resolution.
When the window is placed entirely on a display everything works fine, but
if a window is shared by multiple displays, in a location where
a window is scaled, the correct dimensions can not be safely evaluated
and then we can still get the popup menu cropped. (see images bellow)
**2**) This issue was introduced by the fix for another menu issue that was crashing
Wings3D when closing a window with the context menu …

Fixed the menu location in order to fit on the display it is activated

---

plugins_src/autouv/auv.hrl
plugins_src/autouv/auv_texture.erl
plugins_src/autouv/wpc_autouv.erl

This branch add the option to work with multiples UV tiles in the _AutoUV Editor_ window that is something useful when having complex meshes and when we need to use different texture densities for the object.
The _Create Texture_ option will act over the selected tile and we choose the tile by holding the ALT key while clicking on the desired tile that contains any UV islands.
The _Alignment_, _Scale Max_ and similar commands applied to the islands should be respecting the tile in which it is placed.
It's possible to disable the _Texture Set _mode by toggling this option off. In case we come back to activate it the materials may be reused. (that is a way to restart the texture set mode in case we decide to change the tile's arrangement).
**The workflow should be like this:**
- unwrap the …

Add UV Multiset (tiles)

---

src/wings_geom_win.erl

Fixed a crash in Geometry Graph window when processing the _command_tree_sel_changed_ 
event in a project with multiple folders and objects.  
The origin of the problem could not be found, but the inclusion 
of a validation was able to avoid the hard crash.
This issue was reported by the user @envelupo at Discord and it was 
closing the window during a Snap operation. It was in a setup with 
a couple of folders and objects and as shown in video the Geometry 
Graph starts flicking and then crash: [link Discord](https://discord.com/channels/631099202012708874/1274902097753804892/1312872328232829010)
NOTE:  Preventing Wings3D hard crash on issue related to Geometry Graph 
window update. Thanks to @envelupo

Preventing Wings3D hard crash on issue related to Geometry Graph window

---

plugins_src/commands/wpc_duplicate_radial.erl

NOTE: Fixed axis offset when it was not set. Thanks to ivla

Fixed an issue in Duplicate Radial command

---

plugins_src/commands/wpc_sculpt.erl
src/wings_io.erl
src/wings_render.erl
src/wings_tweak.erl

Fixed the text location in the information line inside the Geometry window which was cutting of the 
text in Linux as well was fixed the misalignment of "Grid Scale" text with the main information text.
The issue was reported by thedæmon in [this post](https://discord.com/channels/631099202012708874/1274902097753804892/1302780415924375624) at Discord.
here is the before and after the fix:
NOTE: Fixed the text location in the information line inside the Geometry window. Thanks to @thedæmon

Fixed the text location in the info line inside the Geometry window

---

src/wings_file.erl

Fixed the autosave status for Revert command after a Revert operation has been used. 
It was reported by **jczd** in this [post](https://discord.com/channels/631099202012708874/1274902097753804892/1318899623829704775) at Discord
NOTE: Fixed the autosave status which was kept "unsaved" after a Revert command be used. Thanks to @jczd

Fixed the autosave status for Revert command

---

unix/wings.appdata.xml

Updated appdata.xml to fix some errors of the flatpak lint

Fixes to appdata for v2.4

---

plugins_src/import_export/wpc_lwo.erl

I've updated the lwo plugin:
LWO3 import added.
LWOB import also added since it seems a much simpler file format
LWO2 import got improvements (added texture support, more material attributes, UV, color attributes)
LXOB was not changed much but was tested to make sure it still works.
NOTE: Improved lwo importer, added LWO3

wpc_lwo: LWO3 Import
